### PR TITLE
Add Elug-sp

### PR DESCRIPTION
**Pull request by heliohead**

### CODE REVIEW

**Comment by igas** [comment]
HNY @heliohead! Thanks for contribution. Just one fix, add your github name to users map please.

**Comment by HashNuke** [comment]
@heliohead Looks like you have the group name in the elixir-users map too. That map is only for real people.

\\cc: @igas

**Comment by heliohead** [comment]
My bad.
Fixed.

**Comment by igas** [comment]
:+1:

**Pull request merged**
