### PR TITLE
Add Szymon Jeż (in Gdańsk, Poland) to users list

### PR DESCRIPTION
**Pull request by jeznet**

### CODE REVIEW

**Comment by igas** [comment]
@jeznet sorry, but github use different order of `lat`, `long`, you need to swap them. You can see rich diff on maps https://github.com/HashNuke/elixir-users/pull/42/files?short_path=3b76934#diff-3b7693476b85ae00138d89225d0b19c9

**Comment by jeznet** [comment]
@igas it's fixed now

**Comment by igas** [comment]
@jeznet can you rebase please? I can't merge it.

**Comment by jeznet** [comment]
@igas done

**Comment by igas** [comment]
:+1:

**Pull request merged**
